version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install depenencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            cd test
            python test.py

  build-windows-exe:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install depenencies
          command: |
            pip install -r requirements.txt
            pip install pyinstaller
      - run:
          name: Compile windows executable
          command: |
            cd src
            pyinstaller decode.py --onefile
      - persist_to_workspace:
          root: .
          paths:
            - src/dist/*

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Publish executable on GitHub
          command: |
            ls -la
            cd src/dist/decode/
            ls -la
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./

workflows:
  decoder:
    jobs:
      - test
      - build-windows-exe
      - publish-github-release:
          requires:
            - build-windows-exe