version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - attach_workspace:
          at: C:/Python/Lib/
      - run:
          name: "Compile windows executable"
          shell: powershell.exe
          command: |
            cd src
            pyinstaller decode.py --onefile
      - persist_to_workspace:
          root: ./
          paths:
            - src/dist/

  install-requirements:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Upgrade pip & Install requirements"
          shell: powershell.exe
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: "test"
          shell: powershell.exe
          command: |
            cd C:/Python27amd64/Lib/
            dir
            cd C:/Python27/Lib/
            dir
      - run:
          name: "test"
          shell: powershell.exe
          command: |
            cd C:/Users/circleci/AppData/Local/Programs/
            dir

  publish:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "install github cli"
          shell: powershell.exe
          command: choco install gh
      - run:
          name: "github create release"
          shell: powershell.exe
          command: gh release create $Env:CIRCLE_BRANCH.split("/")[1] src\dist\decode.exe

  test-native:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - attach_workspace:
          at: C:/Python/Lib/
      - run:
          name: "Testing decode"
          shell: powershell.exe
          command: |
            cd test
            python test.py

  test-windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Update pip"
          shell: powershell.exe
          command: python -m pip install --upgrade pip
      - run:
          name: "Upgrade pip & Install requirements"
          shell: powershell.exe
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: "Testing decode"
          shell: powershell.exe
          command: |
            cd test
            python test.py -s="..\src\dist\decode.exe"

workflows:
  decoder:
    jobs:
      - install-requirements
      - build:
          requires:
            - install-requirements
      - test-native:
          requires:
            - install-requirements
      - test-windows:
          requires:
            - build
      - publish:
          requires:
            - test-native
            - test-windows
          filters:
            branches:
              only: /^release.*$/


