version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            cd test
            python test.py

  build-windows-exe:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install depenencies
          command: |
            pip install pyinstaller
            apt-get install python-dev python3-dev
      - run:
          name: Compile windows executable
          command: |
            cd src
            pyinstaller decode.py --onefile
      - store_artifacts:
          path: /src/dist

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Publish executable on GitHub
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  decoder:
    jobs:
      - test
      - build-windows-exe
      - publish-github-release:
          requires:
            - build-windows-exe